version: '3.8'

services:
  cache:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data_container:/data
  database:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017
  api:
    container_name: api
    tty: true
    build:
      context: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    depends_on: 
      - cache
      - database
volumes:
  mongodb_data_container:
  redis_data_container: